name: swift-algorithms ci
on:
  push:
    branches:
      - '*'
  workflow_dispatch:
  pull_request:
    branches:
      - '*'
jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Setup Swift on Windows"
        uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-6.1-release
          tag: 6.1-RELEASE
      - name: Verify Swift
        run: swift --version
      - name: Archive Swift
        uses: actions/upload-artifact@v4
        with:
          name: swift-windows
          path: |
            C:\Users\runneradmin\AppData\Local\Programs\Swift\Platforms\6.1.0\Windows.platform\Developer\SDKs\Windows.sdk\


