name: swift-windows-package
on:
  push:
    branches:
      - '*'
  workflow_dispatch:
  pull_request:
    branches:
      - '*'
jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Setup Swift on Windows"
        uses: compnerd/gha-setup-swift@main
        with:
          # https://download.swift.org/development/windows10/swift-DEVELOPMENT-SNAPSHOT-2025-03-28-a/swift-DEVELOPMENT-SNAPSHOT-2025-03-28-a-windows10.exe
          branch: main
          tag: swift-DEVELOPMENT-SNAPSHOT-2025-03-28-a
          #branch: swift-6.1-release
          #tag: 6.1-RELEASE
      - name: Verify Swift
        run: swift --version
      - name: Archive Swift
        uses: actions/upload-artifact@v4
        with:
          name: swift-windows
          path: |
            C:\Users\runneradmin\AppData\Local\Programs\Swift


